include(bash/image/image.pri)
include(bash/ffmpeg/ffmpeg.pri)
include(bash/youtube-dl/youtube-dl.pri)

include(bash/generate/Topaz/Topaz.pri)
include(bash/generate/Freepik/Freepik.pri)
include(bash/generate/fal/fal.pri)
include(bash/generate/Luma/Luma.pri)
include(bash/generate/LivePortrait/LivePortrait.pri)
include(bash/generate/FaceFusion/FaceFusion.pri)
